### ISSUE TITLE
Can you share the CAD design files?

### ISSUE THREAD

**Issue by Dave-Man-Dave-UST** [robr345/Ben-Eater-6502#2]
Hi

Firstly can I say thanks for open sourcing the PCD design. Would it be possible for you to share the CAD project files for the PCB. I ask as I would like to fork your repro and add the serial interface to the PCB, and using your starting point would make that a lot easier.

Thanks in advance

Regards

David

**Comment by robr345** [comment]
I have an updated PCB with serial support in the works.
New boards were received from china a few days ago and I will build and test a board in the next few days.
If successfull I will upload the new design to github along with the easyeda design file so people can make changes in the future.
